export default {
  _styles: [
    { width: "160px", backgroundColor: "#000",  zIndex: 100 },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
    { width: "10%" },
  ],
  _template: "provider-statistics",
  head: [
    { title: "Login" },
    { title: "Id" },
    { title: "Name" },
    { title: "ProfitPercent" },
    { title: "Bets Count" },
    { title: "Canceled bets" },
    { title: "Debit amount" },
    { title: "Win amount" },
    { title: "Profit amount" },
    { title: "Agent Commission" },
    { title: "Master Commission" },
    { title: "System Commission" },
    { title: "Discount" },
  ],
  body: []
};
